apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ratings-api
  namespace: ratingsapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ratings-api
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30