apiVersion: v1
kind: Service
metadata:
  name: ratings-api
  namespace: ratingsapp
spec:
  selector:
    app: ratings-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP